demo:
  outputs:
    dev:
      dataset: demodevdwh
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile: ./../demo.json
      location: europe-west1
      method: service-account
      priority: interactive
      project: "{{ env_var('PROJECT') }}"
      threads: 2
      type: bigquery
  target: dev
